/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface BribeInterface extends ethers.utils.Interface {
  functions: {
    "acceptBribe()": FunctionFragment;
    "bribe()": FunctionFragment;
    "claimBribe()": FunctionFragment;
    "numParticipants()": FunctionFragment;
    "toReceiveBribe()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptBribe",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bribe", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimBribe",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numParticipants",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toReceiveBribe",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptBribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bribe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimBribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toReceiveBribe",
    data: BytesLike
  ): Result;

  events: {};
}

export class Bribe extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: BribeInterface;

  functions: {
    acceptBribe(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "acceptBribe()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bribe(overrides?: CallOverrides): Promise<[BigNumber]>;

    "bribe()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    claimBribe(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "claimBribe()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    numParticipants(overrides?: CallOverrides): Promise<[BigNumber]>;

    "numParticipants()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    toReceiveBribe(overrides?: CallOverrides): Promise<[BigNumber]>;

    "toReceiveBribe()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  acceptBribe(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "acceptBribe()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bribe(overrides?: CallOverrides): Promise<BigNumber>;

  "bribe()"(overrides?: CallOverrides): Promise<BigNumber>;

  claimBribe(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "claimBribe()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  numParticipants(overrides?: CallOverrides): Promise<BigNumber>;

  "numParticipants()"(overrides?: CallOverrides): Promise<BigNumber>;

  toReceiveBribe(overrides?: CallOverrides): Promise<BigNumber>;

  "toReceiveBribe()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    acceptBribe(overrides?: CallOverrides): Promise<void>;

    "acceptBribe()"(overrides?: CallOverrides): Promise<void>;

    bribe(overrides?: CallOverrides): Promise<BigNumber>;

    "bribe()"(overrides?: CallOverrides): Promise<BigNumber>;

    claimBribe(overrides?: CallOverrides): Promise<void>;

    "claimBribe()"(overrides?: CallOverrides): Promise<void>;

    numParticipants(overrides?: CallOverrides): Promise<BigNumber>;

    "numParticipants()"(overrides?: CallOverrides): Promise<BigNumber>;

    toReceiveBribe(overrides?: CallOverrides): Promise<BigNumber>;

    "toReceiveBribe()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    acceptBribe(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "acceptBribe()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bribe(overrides?: CallOverrides): Promise<BigNumber>;

    "bribe()"(overrides?: CallOverrides): Promise<BigNumber>;

    claimBribe(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "claimBribe()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    numParticipants(overrides?: CallOverrides): Promise<BigNumber>;

    "numParticipants()"(overrides?: CallOverrides): Promise<BigNumber>;

    toReceiveBribe(overrides?: CallOverrides): Promise<BigNumber>;

    "toReceiveBribe()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptBribe(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "acceptBribe()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bribe(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "bribe()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    claimBribe(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "claimBribe()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    numParticipants(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "numParticipants()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    toReceiveBribe(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "toReceiveBribe()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
