/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SchellingInterface extends ethers.utils.Interface {
  functions: {
    "commit(bytes32)": FunctionFragment;
    "distribute()": FunctionFragment;
    "generateHash(string,uint256)": FunctionFragment;
    "getMajority()": FunctionFragment;
    "reveal(string,uint256)": FunctionFragment;
    "seeCommit()": FunctionFragment;
    "setRevealingState()": FunctionFragment;
    "showCurrentState()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "commit", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "distribute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "generateHash",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMajority",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reveal",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "seeCommit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setRevealingState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "showCurrentState",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "commit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "generateHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMajority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reveal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "seeCommit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRevealingState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "showCurrentState",
    data: BytesLike
  ): Result;

  events: {};
}

export class Schelling extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SchellingInterface;

  functions: {
    commit(
      h: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "commit(bytes32)"(
      h: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    distribute(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "distribute()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    generateHash(
      nonce: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "generateHash(string,uint256)"(
      nonce: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMajority(overrides?: CallOverrides): Promise<[number]>;

    "getMajority()"(overrides?: CallOverrides): Promise<[number]>;

    reveal(
      nonce: string,
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "reveal(string,uint256)"(
      nonce: string,
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    seeCommit(overrides?: CallOverrides): Promise<[string]>;

    "seeCommit()"(overrides?: CallOverrides): Promise<[string]>;

    setRevealingState(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setRevealingState()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    showCurrentState(overrides?: CallOverrides): Promise<[number]>;

    "showCurrentState()"(overrides?: CallOverrides): Promise<[number]>;
  };

  commit(
    h: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "commit(bytes32)"(
    h: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  distribute(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "distribute()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  generateHash(
    nonce: string,
    val: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "generateHash(string,uint256)"(
    nonce: string,
    val: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getMajority(overrides?: CallOverrides): Promise<number>;

  "getMajority()"(overrides?: CallOverrides): Promise<number>;

  reveal(
    nonce: string,
    val: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "reveal(string,uint256)"(
    nonce: string,
    val: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  seeCommit(overrides?: CallOverrides): Promise<string>;

  "seeCommit()"(overrides?: CallOverrides): Promise<string>;

  setRevealingState(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setRevealingState()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  showCurrentState(overrides?: CallOverrides): Promise<number>;

  "showCurrentState()"(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    commit(h: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    "commit(bytes32)"(
      h: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    distribute(overrides?: CallOverrides): Promise<void>;

    "distribute()"(overrides?: CallOverrides): Promise<void>;

    generateHash(
      nonce: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "generateHash(string,uint256)"(
      nonce: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getMajority(overrides?: CallOverrides): Promise<number>;

    "getMajority()"(overrides?: CallOverrides): Promise<number>;

    reveal(
      nonce: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "reveal(string,uint256)"(
      nonce: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    seeCommit(overrides?: CallOverrides): Promise<string>;

    "seeCommit()"(overrides?: CallOverrides): Promise<string>;

    setRevealingState(overrides?: CallOverrides): Promise<void>;

    "setRevealingState()"(overrides?: CallOverrides): Promise<void>;

    showCurrentState(overrides?: CallOverrides): Promise<number>;

    "showCurrentState()"(overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    commit(
      h: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "commit(bytes32)"(
      h: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    distribute(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "distribute()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    generateHash(
      nonce: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "generateHash(string,uint256)"(
      nonce: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMajority(overrides?: CallOverrides): Promise<BigNumber>;

    "getMajority()"(overrides?: CallOverrides): Promise<BigNumber>;

    reveal(
      nonce: string,
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "reveal(string,uint256)"(
      nonce: string,
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    seeCommit(overrides?: CallOverrides): Promise<BigNumber>;

    "seeCommit()"(overrides?: CallOverrides): Promise<BigNumber>;

    setRevealingState(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setRevealingState()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    showCurrentState(overrides?: CallOverrides): Promise<BigNumber>;

    "showCurrentState()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    commit(
      h: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "commit(bytes32)"(
      h: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    distribute(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "distribute()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    generateHash(
      nonce: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "generateHash(string,uint256)"(
      nonce: string,
      val: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMajority(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getMajority()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    reveal(
      nonce: string,
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "reveal(string,uint256)"(
      nonce: string,
      val: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    seeCommit(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "seeCommit()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setRevealingState(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setRevealingState()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    showCurrentState(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "showCurrentState()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
